### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by nongdenchet** [phoenixnghi/CS_Andr_pre-work#1]
Hi I cannot see any code on your repo, could you check? Thank you

**Comment by phoenixnghi** [comment]
hi Quân, 

I've just updated my repo, hope I can finish the pre-work in time :D

**Comment by nongdenchet** [comment]
Hi Nghi, nice to see you again. Would be nice if you implement all the require feature and some of the optinal stuffs. Because we have received many good submissions so you need to do more than this

**Comment by phoenixnghi** [comment]
Hi Quân,

I'm sorry for wasting your time because I'm afraid that I don't have enough time to follow the course this time.
But I will register for the next courses because I'm an Android fanboy :P
I really admire Quân for being good at many fields such as Android, RoR, etc..

See you.

PNghi.

**Comment by nongdenchet** [comment]
No problems, I hope to see you soon man!!!!!! I have heard that you choose Node.js class, best wishes for you
